#!/bin/bash
echo "####################"
echo "Test switches"
echo "####################"
read -p "What is the store #?: " STORE
ping "m"$STORE"sps01.unix.ctcwest.ctc" -c 2 
stor="m"$STORE"sps01.unix.ctcwest.ctc"
stor1=`getent hosts $stor | awk {'print $1'}`
stor3=`echo "$stor1" | cut -d "." -f1-3`

if [[ `ping "m"$STORE"sps01.unix.ctcwest.ctc" -c 4 -q` ]]; then	echo "########################"
    echo " Only start VM if you can’t ping, will now close program "
    echo "########################"
    sleep 3
    break
fi

until [[ $SO =~ y|Y(es)$? ]]; do	 
echo "what is your ssh username: " SSHU	
echo "did you type it correctly? " SO
done



echo "IP is $stor3"

while true; do
	echo
	echo "Testing switches and whatnot"
